name: eShopOnWeb - Code Index

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Verify Solution File
      run: |
        if [ ! -f ./Everything.sln ]; then
          echo "Solution file not found!"
          exit 1
        fi

    - name: Build with dotnet
      run: dotnet build ./Everything.sln --configuration Release /bl

    - name: Index with Rich Code Navigation
      uses: microsoft/RichCodeNavIndexer@v0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        languages: 'csharp'
        environment: 'internal'
